# Part4

In [1]:
import json
from urllib.request import urlopen
import requests,json,os,sys,time,re
import pandas as pd
import numpy as np

In [2]:
def show_work_status(singleCount, totalCount, currentCount):
    currentCount+=singleCount
    percentage=1.*currentCount/totalCount*100
    status='>'*int(percentage/2)+'-'*(50-int(percentage/2))
    if percentage % 3:
        sys.stdout.write('\rStatus:[{0}]{1:.2f}%'.format(status,percentage))
        sys.stdout.flush()
    if percentage>=100: print('\n')

In [3]:
r_part4=requests.get('http://steamspy.com/api.php?request=top100forever')
#r=requests.get('http://steamspy.com/api.php?request=all')
r_part4.content
dic_part4 = r_part4.json()
#dic_part4("median_forever")

We use median playing time for each games here

In [4]:
total_count = 0
with open('app_part4.csv','w') as part_four:
    for game_id, game_details in dic_part4.items():
        total_count = total_count+1
        part_four.write(json.dumps({game_id:game_details}))
        part_four.write('\n')
        
dic_game_time = {'appid':{},'name':{},'median_forever':{}}
current_count = 0
for game_id,game_details in dic_part4.items():
    if game_details!={} and game_details is not None:
        dic_game_time['appid'].update({game_id:game_details.get("appid",{})})
        dic_game_time['name'].update({game_id:game_details.get('name',{})})
        dic_game_time['median_forever'].update({game_id:game_details.get('median_forever',{})})
    show_work_status(1,total_count,current_count)
    current_count+=1

Status:[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00%

In [5]:
appid = list(dic_game_time.get('appid').values())
name = list(dic_game_time.get('name').values())
mid_time = list(dic_game_time.get('median_forever').values())

In [6]:
df_user_links = pd.DataFrame(columns=['Links'])

We have to sotre users' personal links one by one, because there is no dataset shows some users' personal links

In [7]:
#df_user_links['Links'].loc[0] = 'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561197960434622'+'&format=json'
#df_user_links['Links'].loc[1] = 'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561197960434622'+'&format=json'

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561197960434622'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198016215597'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198202525417'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198089202086'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198029242928'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198014403181'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198207433511'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561197966611389'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198077345441'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198089768783'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

new_row = {'Links':'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=12342C69B72B036F8E660D95F28DF431&steamid=76561198024696613'+'&format=json'}
df_user_links = df_user_links.append(new_row, ignore_index=True)

df_user_links

                                                Links
0   http://api.steampowered.com/IPlayerService/Get...
1   http://api.steampowered.com/IPlayerService/Get...
2   http://api.steampowered.com/IPlayerService/Get...
3   http://api.steampowered.com/IPlayerService/Get...
4   http://api.steampowered.com/IPlayerService/Get...
5   http://api.steampowered.com/IPlayerService/Get...
6   http://api.steampowered.com/IPlayerService/Get...
7   http://api.steampowered.com/IPlayerService/Get...
8   http://api.steampowered.com/IPlayerService/Get...
9   http://api.steampowered.com/IPlayerService/Get...
10  http://api.steampowered.com/IPlayerService/Get...

In [8]:
game_play_median = pd.DataFrame(dic_game_time)
game_play_median = game_play_median.rename(columns={'median_forever': 'Midian_playtime(min)'})
#game_play_median
#df = get_df(requests.get(df_user_links['Links'][0]))
#df.head(5)

In [9]:
##########################     Get the playtime data      ############################
def get_df(aa):
    ss = aa.json()
    sd = pd.DataFrame(ss['response']['games'])
    #sd.drop(sd.columns[[1,3, 4, 5]], axis = 1, inplace = True)

    no_zero = sd.loc[sd['playtime_forever']!=0]
#ddf_col = pd.concat([aaaa,game_play_median], axis=1)
    df_col = pd.merge(no_zero, game_play_median, on="appid")
    return df_col

Here we assume users' ratings for games by comparing their playing time for the game with the game's medium total playing time by other users. And get the ratings from 1 to 5. As we use http requests for these users, so their playing time is dynamic thus their ratings is also dynamic

In [10]:
######################## Assume the ratings  ###############
def get_ratings(df_col):
    df_col['Assuming_Ratings'] = 0
    for i in range(len(df_col)):
        if df_col['playtime_forever'][i]>= df_col['Midian_playtime(min)'][i]:
            df_col['Assuming_Ratings'][i] = 5
    #else:
     #   df_col['Assuming_Ratings'][i] = 2
        elif df_col['Midian_playtime(min)'][i]>df_col['playtime_forever'][i]>= df_col['Midian_playtime(min)'][i]*0.8:
            df_col['Assuming_Ratings'][i] = 4
        elif df_col['Midian_playtime(min)'][i]*0.8>df_col['playtime_forever'][i]>= df_col['Midian_playtime(min)'][i]*0.5:
            df_col['Assuming_Ratings'][i] = 3
        elif df_col['Midian_playtime(min)'][i]*0.5>df_col['playtime_forever'][i]>= df_col['Midian_playtime(min)'][i]*0.1:
            df_col['Assuming_Ratings'][i] = 2
        elif df_col['Midian_playtime(min)'][i]*0.1>df_col['playtime_forever'][i]:
            df_col['Assuming_Ratings'][i] = 1
    return df_col

In [11]:
def RDD_csv(df_col,i):
    df_col_text = df_col
    #df_col_text.drop(df_col_text.columns[[1,3]], axis = 1, inplace = True)
    #df_col_text.insert(0, "user_id",i)
    df_col_text['user_id'] = i 
    return df_col_text
#df_col_text_a4 = df_col_a4
#df_col_text_a4.drop(df_col_text_a4.columns[[1,3]], axis = 1, inplace = True)
#df_col_text_a4.insert(0, "user_id",4)

In [86]:
#############################        To assume a dataframe format        ##############################
df_col_text_ = []
df_col_a1 = get_ratings(get_df(requests.get(df_user_links['Links'][0])))
df_col_text_ = RDD_csv(df_col_a1,0)
df_col_text_.drop(df_col_text_.index[0:len(df_col_text_)],axis = 0)    ###########      Remove all the rows in a dataframe        ########
#len(df_col_text_ )     See the number of rows in dataframe  
#df_col_text_

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Empty DataFrame
Columns: [appid, playtime_2weeks, playtime_forever, playtime_linux_forever, playtime_mac_forever, playtime_windows_forever, name, Midian_playtime(min), Assuming_Ratings, user_id]
Index: []

In [87]:
df_col_text_ = df_col_text_.drop(df_col_text_.index[0:len(df_col_text_)],axis = 0) 
df_col_text_

Empty DataFrame
Columns: [appid, playtime_2weeks, playtime_forever, playtime_linux_forever, playtime_mac_forever, playtime_windows_forever, name, Midian_playtime(min), Assuming_Ratings, user_id]
Index: []

In [88]:
##############    To repeat, from here     ########################
for i in range(8):
    
    df_col_ = get_ratings(get_df(requests.get(df_user_links['Links'][i])))    ###### Anti_crawler when i >= 9
    
    df_col_text_element = RDD_csv(df_col_,i)
    df_col_text_ = df_col_text_.append(df_col_text_element)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [44]:
df_col_text_

,Assuming_Ratings,Midian_playtime(min),appid,name,playtime_2weeks,playtime_forever,playtime_linux_forever,playtime_mac_forever,playtime_windows_forever,user_id
0,2,218,10,Counter-Strike,NaN,32,0,0,0,0
1,2,22,30,Day of Defeat,NaN,6,0,0,6,0
2,2,179,50,Half-Life: Opposing Force,NaN,52,0,0,0,0
3,5,156,70,Half-Life,NaN,412,9,0,45,0
4,1,146,130,Half-Life: Blue Shift,NaN,1,0,0,0,0
5,5,314,220,Half-Life 2,NaN,1091,26,0,17,0
6,1,575,240,Counter-Strike: Source,NaN,48,0,0,0,0
7,2,185,300,Day of Defeat: Source,NaN,64,0,0,0,0
8,4,88,320,Half-Life 2: Deathmatch,NaN,76,0,0,0,0
9,2,24,340,Half-Life 2: Lost Coast,NaN,6,0,0,0,0
10,3,189,380,Half-Life 2: Episode One,NaN,151,0,0,9,0
11,3,182,400,Portal,NaN,107,0,0,0,0
12,5,210,500,Left 4 Dead,NaN,1704,0,0,0,0
13,5,614,550,Left 4 Dead 2,NaN,1480,0,0,0,0
14,5,477,620,Portal 2,NaN,1154,0,0,0,0
15,1,8103,730,Counter-Strike: Global Offensive,NaN,654,0,0,73,0
16,2,350,1046930,Dota Underlords,NaN,115,0,0,1,0
17,1,3237,8930,Sid Meier's Civilization V,NaN,265,0,0,0,0
18,4,1606,105600,Terraria,NaN,1355,0,0,0,0
19,4,2941,72850,The Elder Scrolls V: Skyrim,NaN,2710,0,0,0,0
20,2,275,204360,Castle Crashers,NaN,53,0,0,0,0
21,2,707,49520,Borderlands 2,NaN,113,0,0,0,0
22,2,238,219640,Chivalry: Medieval Warfare,NaN,52,0,0,0,0
23,2,379,230410,Warframe,NaN,71,0,0,0,0
24,5,293,238960,Path of Exile,NaN,938,0,0,748,0
25,1,2690,252490,Rust,NaN,207,0,0,0,0
26,1,2100,261550,Mount & Blade II: Bannerlord,NaN,30,0,0,30,0
27,2,5542,271590,Grand Theft Auto V,NaN,2013,0,0,102,0
28,1,322,304930,Unturned,NaN,10,0,0,0,0
29,2,1370,239140,Dying Light,NaN,148,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
5,5,210,500,Left 4 Dead,NaN,384,0,0,0,7
6,3,614,550,Left 4 Dead 2,NaN,422,0,0,0,7
7,4,477,620,Portal 2,NaN,476,0,0,0,7
8,5,1606,105600,Terraria,NaN,1947,0,0,0,7
9,5,3237,8930,Sid Meier's Civilization V,NaN,6403,0,0,0,7
10,5,102,208090,Loadout,NaN,475,0,0,0,7
11,5,275,204360,Castle Crashers,NaN,959,0,0,0,7
12,5,238,219640,Chivalry: Medieval Warfare,NaN,342,0,0,0,7
13,3,170,218230,PlanetSide 2,NaN,118,0,0,0,7
14,5,134,44350,GRID 2,NaN,1149,0,0,0,7
15,3,687,218620,PAYDAY 2,NaN,354,0,0,0,7
16,3,2690,252490,Rust,NaN,1855,0,0,0,7
17,3,1827,227300,Euro Truck Simulator 2,NaN,1136,0,0,0,7
18,5,458,203160,Tomb Raider,NaN,1775,0,0,0,7
19,5,217,278360,A Story About My Uncle,NaN,1160,0,0,0,7
20,5,237,15700,Oddworld: Abe's Oddysee,NaN,1825,0,0,0,7
21,1,8103,730,Counter-Strike: Global Offensive,NaN,536,0,0,0,7
22,2,574,322330,Don't Starve Together,NaN,108,0,0,0,7
23,5,143,319630,Life is Strange - Episode 1,NaN,3571,0,0,0,7
24,2,661,255710,Cities: Skylines,NaN,157,0,0,0,7
25,4,5542,271590,Grand Theft Auto V,NaN,5095,0,0,0,7
26,5,322,363970,Clicker Heroes,NaN,9469,0,0,0,7
27,5,2080,377160,Fallout 4,NaN,4764,0,0,0,7
28,2,846,381210,Dead by Daylight,NaN,379,0,0,0,7
29,2,707,49520,Borderlands 2,NaN,162,0,0,0,7
30,5,1542,413150,Stardew Valley,NaN,4635,0,0,0,7
31,5,3584,359550,Tom Clancy's Rainbow Six Siege,NaN,27017,0,0,575,7
32,5,1164,292030,The Witcher 3: Wild Hunt,NaN,10299,0,0,0,7
33,5,350,1046930,Dota Underlords,NaN,1230,0,0,0,7
34,1,932,632360,Risk of Rain 2,NaN,48,0,0,0,7

In [89]:
set(df_col_text_['user_id'])

{0, 1, 2, 3, 4, 5, 6, 7}

In [78]:
########################     Choose the columns that we need and store them as CSV      #######################

user_rating_df = pd.read_csv("df_col_use_app_raings_new.csv")
user_rating_df.head(5)
user_rating_df = user_rating_df.drop(['Unnamed: 0'], axis=1)

In [82]:
#list_user_name = list(set(user_rating_df['user_id']))
#list_appid_name = list(set(user_rating_df['appid']))

from scipy.spatial.distance import cosine
from pandas import DataFrame


df = DataFrame({"col1": [158, 25, 180, 152, 96],
                "col2": [173, 191, 33, 165, 108]})

print(1 - cosine(df["col1"], df["col2"]))

0.7498213004921095

In [83]:
a0 = pd.DataFrame()
for i in range(8):
    #a0 = user_rating_df.loc[user_rating_df['user_id']==0]
    #a0 = a0.rename(columns={'Assuming_Ratings': 0})
    #a0 = a0.drop(['user_id'], axis=1)
#aa = a0.set_index('appid', inplace=True)
    a1 = user_rating_df.loc[user_rating_df['user_id']==i]
    a1 = a1.rename(columns={'Assuming_Ratings': 'ratings'})
    #a1 = a1.drop(['user_id'], axis=1)
#a1 = a1.set_index('appid', inplace=True)
    
    a0 = pd.concat([a0, a1], axis=0)

In [90]:
df = a0.pivot('appid', 'user_id','ratings')
df.head(5)
df.fillna(0.0, inplace = True)#################   Fill all the data with 0    ######################

ValueError: Index contains duplicate entries, cannot reshape

In [92]:
from scipy.spatial.distance import cosine    ##################    1 - Cosine
from pandas import DataFrame
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html
aaa = {}
for i in range(8):
    for j in range(8):
        a = 1 - cosine(df[i], df[j])
        #a = a.tolist()
        aaa.update({i:[a, j ]for j in range(8)})
aaa

KeyError: 0

In [93]:
asd = pd.DataFrame(aaa)
asd

Empty DataFrame
Columns: []
Index: []